import Head from 'next/head'

import styles from '../components/custom/Section.module.css'

import Photo from '../components/custom/Photo'
import Section from '../components/custom/Section'
import Container from '../components/custom/Container'
import SectionList from '../components/custom/SectionList'
import SectionText from '../components/custom/SectionText'

import {
  personInfo,
  personData,
  educationBackground,
  tranningCourses,
  workExperinces,
  workSkills,
  languages,
  hobbies,
} from '../data/cvData'

const formatDate = (date) => {
  if (!date) {
    return 'Present'
  }

  const dateKeys = date.split('-')
  if (dateKeys && dateKeys.length == 2) {
    const dateObj = new Date(`${dateKeys[1]}-${dateKeys[0]}`)
    const dateFmt = dateObj.toDateString()
    return `${dateFmt.substring(4, 7)} ${dateFmt.substring(11, 15)}`
  }
  //   return moment(date, 'MM-YYYY').format('MMM YYYY')
}

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Vannaravuth YO's CV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous"
        />
      </Head>

      <main>
        <header>
          <div className={styles.TitleContainer}>
            <h1>Curriculum Viate</h1>
            <h3>{personInfo.position}</h3>
          </div>
          <div className={styles.AddressContainer}>
            <div>
              <Photo />
            </div>
            <div>
              <address className={styles.Address}>
                <span className={styles.FullName}>
                  {personInfo.firstName} {personInfo.lastName}
                </span>
                {personInfo.address &&
                  personInfo.address.map((add) => <span key={add}>{add}</span>)}
                <span>
                  <a href={`tel:${personInfo.phone}`}>{personInfo.phone}</a>
                </span>
                <span>
                  <a href={`mailto:${personInfo.email}`}>{personInfo.email}</a>
                </span>
              </address>
            </div>
          </div>
        </header>

        <SectionList title="Personal Data" items={personData} />

        <Section title="Work Experience">
          <ul className={styles.List}>
            {workExperinces &&
              workExperinces.map((item, index) => (
                <li key={index}>
                  <div className={styles.ListItem}>
                    <div className={styles.ListItemLeft}>
                      {formatDate(item.date[0])} - {formatDate(item.date[1])}
                    </div>
                    <div className={styles.ListItemRight}>
                      {item.position}
                      {item.company && (
                        <span>
                          {' at '}
                          <strong>{item.company}</strong>
                        </span>
                      )}
                      {item.children && (
                        <ul className={styles.ListSubItem}>
                          {item.children.map((child, key) => (
                            <li key={key}>{child}</li>
                          ))}
                        </ul>
                      )}
                    </div>
                  </div>
                </li>
              ))}
          </ul>
        </Section>

        <SectionList title="Education Background" items={educationBackground} />

        <SectionList title="Tranning Courses" items={tranningCourses} />

        <SectionList title="Skills" items={workSkills} />

        <SectionList title="Languages" items={languages} />

        <SectionText title="Hobbies" text={hobbies} />
      </main>
    </Container>
  )
}
